### ISSUE TITLE
Suggestion: DW effects support (yes my addon)

### ISSUE THREAD

**Issue by Nikitaf93** [CraftPig/sweps_eft_meds#1]
Add support for my addons effects for [this](https://steamcommunity.com/sharedfiles/filedetails/?id=3360051476&searchtext=decaying+winter) addon

Here's the list of what should heal what
Aluminium splint = broken leg and should add the Splint effect
Hemostatic tourniquet = remove Arterial bleeding
L1 norepinephrine = remove Morale

ps here's the effect names
ArterialBleed
BrokenLeg
Morale
Splint
PatchedUp
Tourniquet
Intoxicated
Vomiting

**Comment by Nikitaf93** [comment]
if you need an effects description tell me

**Comment by Wolf48911** [comment]
@Nikitaf93  oh i did this lol. just more inline with the Tarkov handles broken legs and bleeds (not using Splint, PatchedUp, and Tourniquet)

**Comment by CraftPig** [comment]
The addon primarily makes use of the base effects from SEF and doesn't actually aim to add new effects or new injury mechanics.
The splints etc cure effects that make sense and are similar to the game.

**Comment by CraftPig** [comment]
Currently not planning to do this.
